theme = "cactus"
title = "Max Newcomer"
baseURL = "https://maxwnewcomer.github.io"
[params]
colortheme = "dark"
description = "I'm a software engineer/data scientist skilled in optimization with 3 years of relevant experience creating machine learning models, retraining systems and transforming data science prototypes to production-grade solutions. I'm graduating in the fall of 2022 from the University of Wisconsin - Madison with majors in Computer Science, Mathematics, and Data Science. I look forward to applying my skills and learning much more as I continue my career in the Computer Science and Data Science fields!"
mainSection = "posts"
mainSectionTitle = "Blog"
showAllPostsOnHomePage = false
postsOnHomePage = 0
showProjectsList = true
projectsUrl = "https://github.com/maxwnewcomer"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4


[[params.social]]
name = "github"
link = "https://github.com/maxwnewcomer"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/maxnewcomer/"

[[params.social]]
name = "orcid"
link = "https://orcid.org/0000-0003-2491-546X"

[[params.social]]
name = "email"
link = "maxwnewcomer@gmail.com"


[[menu.main]]
name = "About Me"
url = "/"
weight = 1

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 2
