theme = "cactus"
title = "Max Newcomer"
baseURL = "https://maxwnewcomer.github.io"
[params]
colortheme = "dark"
description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your website’s end users and an ideal writing experience for website authors."
mainSection = "posts"
mainSectionTitle = "Blog"
showAllPostsOnHomePage = false
postsOnHomePage = 0
showProjectsList = true
projectsUrl = "https://github.com/maxwnewcomer"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4


[[params.social]]
name = "github"
link = "https://github.com/maxwnewcomer"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/maxnewcomer/"

[[params.social]]
name = "orcid"
link = "https://orcid.org/0000-0003-2491-546X"

[[params.social]]
name = "email"
link = "maxwnewcomer@gmail.com"


[[menu.main]]
name = "About Me"
url = "/"
weight = 1

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 2
